<?php
// Phase 1 explicit per-table decisions.
// Format: 'table' => 'module|tier|decision|target|phase|note'
// decision ∈ NODE | EDGE | AGG_EDGE | PROP | EXCLUDE | REVIEW
return [

// ───────────────────────── FOUNDATION (phase 4) ─────────────────────────
'school_setup'          => 'Foundation|A|NODE|:Institute|4|PK `Id`; no sub_institute_id — the PK *is* the tenant. uid Institute:{Id}:0:{Id}',
'academic_section'      => 'Foundation|A|NODE|:AcademicSection|4|',
'academic_year'         => 'Foundation|A|NODE|:AcademicYear|4|Referenced 105× in code; every time-scoped edge hangs off it',
'standard'              => 'Foundation|A|NODE|:Standard|4|',
'subject'               => 'Foundation|A|NODE|:Subject|4|',
'division'              => 'Foundation|A|NODE|:Division|4|`section_id` in enrollment refers here',
'batch'                 => 'Foundation|A|NODE|:Batch|4|',
'school_sections'       => 'Foundation|A|NODE|:SchoolSection|4|Tenant is `school_id`, not the NULL sub_institute_id column (SCHOOL-SECTION-TENANCY 2026-08-11)',
'hrms_departments'      => 'Foundation|A|NODE|:Department|4|',
'tbluserprofilemaster'  => 'Foundation|A|NODE|:Role|4|',
'tblclient'             => 'Foundation|B|NODE|:Client|4|Parent org above Institute',
'grade_master'          => 'Foundation|B|NODE|:GradeScheme|4|',
'house_master'          => 'Foundation|B|NODE|:House|4|',
'student_quota'         => 'Foundation|B|NODE|:Quota|4|q125 — heavily used; also the join key for the fee schedule',
'subject_optional_type' => 'Foundation|B|NODE|:OptionalSubjectType|4|',
'period'                => 'Foundation|B|NODE|:Period|4|Uses `academic_year_id`, not syear',
'sub_std_map'           => 'Foundation|A|EDGE|(:Standard)-[:HAS_SUBJECT]->(:Subject)|4|',
'std_div_map'           => 'Foundation|A|EDGE|(:Standard)-[:HAS_DIVISION]->(:Division)|4|NOT in the master prompt — this is how Standard reaches Division',
'subject_elective'      => 'Foundation|B|EDGE|(:Standard)-[:HAS_ELECTIVE]->(:Subject)|4|',
'division_capacity_master' => 'Foundation|B|PROP|capacity on :Division|4|',
'school_detail'         => 'Foundation|B|PROP|on :Institute|4|',
'institute_detail'      => 'Foundation|B|PROP|on :Institute|4|',
'period_details'        => 'Foundation|B|PROP|on :Period|4|',
'enrollment_prefix_master' => 'Foundation|D|EXCLUDE|—|—|Numbering config, no traversal value',
'tblcity'               => 'Foundation|C|NODE|:City|4|Geography dimension',
'tblstate'              => 'Foundation|C|NODE|:State|4|Geography dimension',
'place_master'          => 'Foundation|C|NODE|:Place|4|',
'religion'              => 'Foundation|C|NODE|:Religion|4|Demographic dimension',
'cast'                  => 'Foundation|C|NODE|:Caste|4|`cast` and `caste` are two live tables — see finding F9',
'caste'                 => 'Foundation|C|NODE|:Caste|4|Duplicate of `cast`; pick one at Phase 2',
'blood_group'           => 'Foundation|C|NODE|:BloodGroup|4|',
'general_data'          => 'Foundation|C|REVIEW|—|4|q40, 189 rows, generic name — needs a human to say what it holds',
'master_setup_select'   => 'Foundation|C|PROP|lookup|4|',
'master_fields'         => 'Foundation|D|EXCLUDE|—|—|Form-builder metadata',
'master_fields_institute' => 'Foundation|D|EXCLUDE|—|—|Form-builder metadata',
'master_fields_table'   => 'Foundation|D|EXCLUDE|—|—|Form-builder metadata',
'erp_status'            => 'Foundation|D|EXCLUDE|—|—|Status lookup',
'template_master'       => 'Foundation|D|EXCLUDE|—|—|Print templates',
'room_type_master'      => 'Operations|C|NODE|:RoomType|12|',
'mst_item_status'       => 'Operations|C|PROP|status lookup|12|',
'normclature'           => 'Foundation|D|EXCLUDE|—|—|',

// ───────────────────────── CURRICULUM (phase 5) ─────────────────────────
'lms_curriculum'        => 'Curriculum|A|NODE|:Curriculum|5|',
'lms_units'             => 'Curriculum|A|NODE|:Unit|5|No tenancy column — derive via curriculum_id',
'chapter_master'        => 'Curriculum|A|NODE|:Chapter|5|**99 rows only, ids 1012-8677.** Gen-2 extraction pipeline. See finding F1',
'topic_master'          => 'Curriculum|A|NODE|:Topic|5|99.4% of chapter_id values dangle — see F1',
'lms_concept'           => 'Curriculum|A|NODE|:Concept|5|1,372 rows, **100% tenant 1**, 0 dangling chapter_id. The one clean spine',
'content_master'        => 'Curriculum|A|NODE|:Content|5|99.0% of chapter_id values dangle — see F1',
'lms_content_category'  => 'Curriculum|B|NODE|:ContentCategory|5|Global reference data — all 21 rows carry sub_institute_id 0 (CATEGORY-SCOPE 2026-08-11)',
'lms_mapping_type'      => 'Curriculum|A|NODE|:MappingType + [:PARENT_OF]|5|Self-referencing taxonomy tree (Blooms, DoK). `type` empty on 99.8%',
'content_mapping_type'  => 'Curriculum|A|EDGE|(:Content)-[:TAGGED_AS]->(:MappingType)|5|No tenancy — derive via content_id',
'lms_lesson_plan'       => 'Curriculum|A|NODE|:Lesson|5|1,803 rows; 99.3% chapter_id dangling',
'lms_lesson_plan_periods' => 'Curriculum|B|NODE|:LessonPeriod|5|',
'lms_lesson_plan_concepts' => 'Curriculum|A|EDGE|(:Lesson)-[:COVERS]->(:Concept)|5|Joins via lms_lesson_plan_periods_id, not lesson_id',
'lms_lessonplan_dayswise' => 'Curriculum|B|EDGE|(:Lesson)-[:SCHEDULED_ON]->(:AcademicYear)|5|',
'lms_learning_outcomes' => 'Curriculum|A|NODE|:LearningObjective|5|No tenancy column — derive via subject_id (LO-TENANCY 2026-08-11; chapter_id path kept 0 of 259)',
'lms_flashcard'         => 'Curriculum|B|NODE|:Flashcard|5|',
'lms_teacher_resource'  => 'Curriculum|B|NODE|:TeacherResource|5|',
'lms_syllabus'          => 'Curriculum|B|NODE|:Syllabus|5|',
'syllabus'              => 'Curriculum|B|NODE|:Syllabus|5|Second syllabus table — reconcile with lms_syllabus at Phase 2',
'lms_assignment'        => 'Curriculum|B|NODE|:Assignment|5|',
'lms_virtual_classroom' => 'Curriculum|B|NODE|:VirtualClassroom|5|',
'lms_portfolio'         => 'Curriculum|B|NODE|:Portfolio|5|',
'lms_doubt'             => 'Curriculum|B|NODE|:Doubt|5|',
'lms_doubt_conversation' => 'Curriculum|B|EDGE|(:Doubt)-[:HAS_REPLY]->(:Doubt)|5|',
'lms_intelligence_lesson_plans' => 'Curriculum|B|NODE|:Lesson|5|AI-generated variant; 4 rows',
'chapter_topic_master'  => 'Curriculum|B|REVIEW|—|5|330 rows, **0 code references**, chapter_ids in the dead id space. Probably Gen-1 residue',
'contents'              => 'Curriculum|B|REVIEW|—|5|48 rows, q31 — distinct from content_master; needs a human call',
'suggested_content'     => 'Curriculum|B|EDGE|(:Content)-[:SUGGESTED_FOR]->(:Concept)|5|',
'knowledge_base'        => 'Curriculum|B|NODE|:KnowledgeBase|5|',
'knowledge_base_detail' => 'Curriculum|B|PROP|on :KnowledgeBase|5|',
'document_extractions'  => 'Curriculum|A|NODE|:Extraction|5|The provenance of the Gen-2 chapters — 108 rows, 98 used by chapter_master',
'semantic_intelligence' => 'Curriculum|B|REVIEW|—|5|88 rows, q16 — unclear role',
'gamma_ppt'             => 'Curriculum|D|EXCLUDE|—|—|Empty',
'classwork_attachment'  => 'Curriculum|B|PROP|attachment_count on :Lesson|5|5,401 rows — file metadata only',
'homework'              => 'Curriculum|B|NODE|:Homework|5|q98',
'book_list'             => 'Curriculum|B|NODE|:TextBook|5|',
'h5p_scenarios'         => 'Curriculum|B|NODE|:H5PScenario|5|',
'h5p_scenario_points'   => 'Curriculum|B|PROP|on :H5PScenario|5|',
'h5p_interactive_video' => 'Curriculum|D|EXCLUDE|—|—|Empty',
'h5p_video_interactions' => 'Curriculum|D|EXCLUDE|—|—|Empty',
'lms_data_content_neo4j' => 'Curriculum|D|EXCLUDE|—|—|**Old migration staging table** (13,693 rows, q2). Do not re-import',
'lms_data_neo4j'        => 'Curriculum|D|EXCLUDE|—|—|Old migration staging (4,131 rows, q0)',
'lms_data_question_neo4j' => 'Curriculum|D|EXCLUDE|—|—|Old migration staging, empty',
'lessonplan'            => 'Curriculum|B|REVIEW|—|5|39 rows, q41 — legacy sibling of lms_lesson_plan',
'lessonplan_execution'  => 'Curriculum|B|REVIEW|—|5|5 rows',
'pal_misconceptions'    => 'Curriculum|A|NODE|:Misconception|5|**2 rows.** The named source for (:Misconception) in Wave 2 — the shape is buildable but carries almost no data',
'lo_master'             => 'LearningOutcome|A|NODE|:LOCategory|5|',
'lo_category'           => 'LearningOutcome|A|NODE|:LOCategoryAlt|5|1 row. **Split from :LOCategory 2026-08-10** — its single (tenant,pk) collides with lo_master',
'lo_indicator'          => 'LearningOutcome|A|NODE|:LearningOutcome|5|1 row',
'learning_outcome_indicator' => 'LearningOutcome|C|NODE|:LOIndicatorRef|5|11 rows — structural pilot. ORPHAN-LABELS 2026-08-11: split from :LearningOutcome and demoted to C. Its STANDARD/SUBJECT columns hold names, not ids, so no parent FK is resolvable; as Tier A it hard-failed G8 with no available remedy',
'learning_outcome_question_master' => 'LearningOutcome|A|EDGE|(:LearningOutcome)-[:ASSESSED_BY]->(:Question)|6|15 rows',
'learning_outcome_student_marks' => 'LearningOutcome|A|EDGE|(:Student)-[:ACHIEVED]->(:LearningOutcome)|9|14 rows',
'learning_outcome_exam_type_master' => 'LearningOutcome|C|NODE|:ExamTypeRef|9|4 rows, columns are ID + EXAM_TYPE only. ORPHAN-LABELS 2026-08-11: split from :ExamType — that label is Tier A via result_exam_master, so these 4 parentless reference rows hard-failed G8 despite having no FK to attach to',
'learning_outcome_pdf'  => 'LearningOutcome|D|EXCLUDE|—|—|Generated PDFs',

// ───────────────────────── QUESTIONS (phase 6) ─────────────────────────
'lms_question_master'   => 'Assessment|A|NODE|:Question|6|**concept_id empty on 99.92%** (62,162/62,209) — ASSESSES_CONCEPT cannot be built from here. See F2',
'lms_question_mapping'  => 'Assessment|A|EDGE|(:Question)-[:TAGGED_AS]->(:MappingType)|6|**NOT chapter/concept mapping** — it is Blooms + Depth-of-Knowledge tagging. See F3',
'answer_master'         => 'Assessment|A|PROP|option_count + correct_answer_id on :Question|6|**Question OPTIONS, not student answers** (3.88 per question). Master prompt misread this. See F4',
'question_paper'        => 'Assessment|A|NODE|:Assessment|6|Has both sub_institute_id and syear — the tenancy anchor for lms_online_exam',
'question_type_master'  => 'Assessment|B|NODE|:QuestionType|6|',
'old_question_category_master' => 'Assessment|D|EXCLUDE|—|—|Legacy, superseded by lms_mapping_type',
'old_question_level_master' => 'Assessment|D|EXCLUDE|—|—|Legacy',
'10_05_question_master' => 'Assessment|D|EXCLUDE|—|—|9 rows, 0 code refs — dated backup table',
'counselling_question_master' => 'Counselling|B|NODE|:Question|6|Separate counselling question bank',
'counselling_answer_master' => 'Counselling|B|PROP|on :Question|6|',
'counselling_question_mapping' => 'Counselling|B|EDGE|(:Question)-[:TAGGED_AS]->(:MappingType)|6|',
'counselling_online_exam' => 'Counselling|B|NODE|:Result|9|35 rows',
'counselling_online_exam_answer' => 'Counselling|B|AGG_EDGE|(:Student)-[:MASTERS]->(:Chapter)|9|45 rows. Aggregates to :Chapter per CONCEPT-LINK',
'counselling_course'    => 'Counselling|B|NODE|:Course|5|',

// ───────────────────────── PEOPLE (phase 7) ─────────────────────────
'tblstudent'            => 'Student|A|NODE|:Student|7|83,715 rows across 48 tenants. **PII** — fold all demographics here; do NOT create :StuDetail (defect D5)',
'tblstudent_enrollment' => 'Student|A|EDGE|(:Student)-[:ENROLLED_IN]->(:Standard) + [:IN_DIVISION]->(:Division)|7|`section_id` is the division FK',
'student_optional_subject' => 'Student|A|EDGE|(:Student)-[:STUDIES]->(:Subject)|7|',
'tblstudent_siblings'   => 'Student|A|EDGE|(:Student)-[:SIBLING_OF]->(:Student)|7|2 rows',
'student_document_type' => 'Student|B|NODE|:DocumentType|7|',
'tblstudent_document'   => 'Student|B|PROP|document_count on :Student|7|66,492 rows of file metadata — projecting as nodes duplicates PII for zero traversal value',
'tblstudent_doc_std_mapping' => 'Student|D|EXCLUDE|—|—|Document/standard join, metadata only',
'tblstudent_family_history' => 'Student|B|NODE|:Guardian|7|10,279 rows — parent/guardian records. **PII**',
'tblstudent_past_education' => 'Student|B|PROP|on :Student|7|',
'tblstudent_tc_details' => 'Student|B|PROP|transfer-certificate fields on :Student|7|',
'tblstudent_parent_feedback' => 'Student|B|EDGE|(:Guardian)-[:GAVE_FEEDBACK]->(:Institute)|7|6 rows',
'tblstudent_bank_detail' => 'Student|D|EXCLUDE|—|—|Bank PII, no traversal value',
'tblstudent_bank_detail_log' => 'Student|D|EXCLUDE|—|—|Audit log',
'tblstudent_payment_method_mapping' => 'Student|D|EXCLUDE|—|—|175,268-row ledger, q5. Payment-method history — MariaDB answers this',
'tblstudent_fees_failure' => 'Student|D|EXCLUDE|—|—|16,786-row failure log',
'student_health'        => 'Student|B|PROP|on :Student|7|**Sensitive PII**',
'student_height_weight' => 'Student|B|AGG_EDGE|(:Student)-[:BIOMETRIC]->(:AcademicYear)|7|9,415-row ledger — aggregate latest per year',
'student_vaccination'   => 'Student|B|PROP|on :Student|7|**Sensitive PII**, 8 rows',
'student_infirmary'     => 'Student|B|AGG_EDGE|(:Student)-[:INFIRMARY_VISITS]->(:AcademicYear)|7|21,373-row ledger. **Sensitive PII**',
'student_anacdotal'     => 'Student|B|AGG_EDGE|(:Student)-[:ANECDOTAL_NOTES]->(:AcademicYear)|7|11,749-row ledger',
'student_capture_attendance' => 'Student|B|EXCLUDE|—|—|130 rows, photo-capture log',
'student_capture_photos' => 'Student|D|EXCLUDE|—|—|Photo metadata',
'student_change_request' => 'Student|D|EXCLUDE|—|—|Workflow log',
'student_change_req_type' => 'Student|D|EXCLUDE|—|—|Lookup',
'STUDENT_CHANGE_REQ_TYPE' => 'Student|D|EXCLUDE|—|—|Case-variant duplicate of student_change_req_type — see F9',
'result_student_attendance_master' => 'Student|A|AGG_EDGE|(:Student)-[:ATTENDANCE]->(:AcademicYear)|7|Aggregate per (student, syear, **term_id**) — there is no month column',
'attendance_student'    => 'Student|B|REVIEW|—|7|18 rows, q26',
'attendance_json_result' => 'Student|D|EXCLUDE|—|—|JSON cache',
'dicipline'             => 'Student|B|EDGE|(:Student)-[:HAS_INCIDENT]->(:DisciplineCategory)|7|19,642 rows. Master prompt said Student→Student — that is wrong, the target is a category',
'dicipline_master'      => 'Student|B|NODE|:DisciplineCategory|7|',
'dicipline_dd'          => 'Student|B|NODE|:DisciplineDropdown|7|42 rows. **Split from :DisciplineCategory 2026-08-10** — 16 (tenant,pk) pairs collide with dicipline_master, so sharing the label silently lost rows',
'class_teacher'         => 'Student|A|EDGE|(:Staff)-[:CLASS_TEACHER_OF]->(:Division)|10|2,924 rows',
'consent_master'        => 'Student|B|NODE|:ConsentType|7|',
'certificate_history'   => 'Student|D|EXCLUDE|—|—|Issue log',
'admission_registration_v1' => 'Admission|B|NODE|:Applicant|7|836 rows',
'admission_registration' => 'Admission|B|NODE|:Applicant|7|5 rows — legacy v0',
'admission_enquiry'     => 'Admission|B|NODE|:Enquiry|7|12 rows, q82',
'new_admission_inquiry_registration' => 'Admission|B|NODE|:Enquiry|7|356 rows',
'admission_category_master' => 'Admission|B|NODE|:AdmissionCategory|7|',
'admission_age_validation' => 'Admission|D|EXCLUDE|—|—|Validation config',
'admission_form'        => 'Admission|D|EXCLUDE|—|—|Empty',
'temp_signup'           => 'Student|D|EXCLUDE|—|—|Signup staging',

// ───────────────────────── ASSESSMENT / RESULT (phases 8-9) ─────────────────────────
'lms_online_exam'       => 'Assessment|A|NODE|:Result|8|147,875 rows but only **1,326 distinct students**. No tenancy column — derive via question_paper_id (21 orphans)',
'lms_online_exam_answer' => 'Assessment|A|AGG_EDGE|(:Student)-[:MASTERS]->(:Chapter)|8|**2,418,015 rows → ~24k-58k edges.** Cannot target :Concept — see F2',
'lms_online_exam_student' => 'Assessment|B|EDGE|(:Student)-[:HAS_RESULT]->(:Result)|8|78 rows',
'lms_online_exam_answer_student' => 'Assessment|B|AGG_EDGE|(:Student)-[:MASTERS]->(:Chapter)|8|723 rows. Aggregates to :Chapter per CONCEPT-LINK',
'lms_offline_exam'      => 'Assessment|B|NODE|:Result|8|2 rows',
'lms_offline_exam_answer' => 'Assessment|B|AGG_EDGE|(:Student)-[:MASTERS]->(:Chapter)|8|5 rows. Aggregates to :Chapter per CONCEPT-LINK',
'result_create_exam'    => 'Result|A|NODE|:Exam|9|33,759 rows',
'result_exam_master'    => 'Result|A|NODE|:ExamType|9|Uses **`SubInstituteId`** (PascalCase) and PK `Id` — loader must special-case',
'result_exam_type_master' => 'Result|B|NODE|:ExamTypeCategory|9|Also PascalCase `SubInstituteId`',
'result_personalize_marks' => 'Result|A|AGG_EDGE|(:Student)-[:SCORED]->(:Exam)|9|**1,308,379 rows → 54,712 edges** (measured). Only 4 tenants / 443 students',
'result_remarks'        => 'Result|A|PROP|remark on the :SCORED edge|9|',
'result_reportcard_marks' => 'Result|B|AGG_EDGE|(:Student)-[:REPORTCARD]->(:Exam)|9|20,865 rows',
'grade_master_data'     => 'Result|A|NODE|:Grade|9|',
'result_co_scholastic'  => 'Result|B|NODE|:CoScholasticArea|9|',
'result_co_scholastic_grades' => 'Result|B|EDGE|(:Student)-[:CO_SCHOLASTIC_GRADE]->(:CoScholasticArea)|9|',
'result_co_scholastic_parent' => 'Result|B|NODE|:CoScholasticArea|9|Parent category',
'result_co_scholatic_range' => 'Result|B|PROP|grade band|9|Note the typo in the table name',
'result_co_scholastic_marks_entries' => 'Result|D|EXCLUDE|—|—|**0 rows but 11 code refs** — see F7',
'result_skillset'       => 'Result|B|NODE|:Skillset|9|q41',
'result_activity_master' => 'Result|B|NODE|:Activity|9|4,664 rows',
'result_activity_group' => 'Result|B|NODE|:ActivityGroup|9|',
'result_activity_marks' => 'Result|D|EXCLUDE|—|—|**0 rows but 21 code refs** — see F7',
'result_sub_activity'   => 'Result|D|EXCLUDE|—|—|**0 rows but 16 code refs** — see F7',
'result_html'           => 'Result|D|EXCLUDE|—|—|**0 rows but 39 code refs** — rendered HTML cache. See F7',
'result_marks'          => 'Result|D|EXCLUDE|—|—|**0 rows but 16 code refs** — see F7',
'result_oldyear_marks'  => 'Result|D|EXCLUDE|—|—|0 rows, 0 refs',
'result_exam_approve'   => 'Result|B|PROP|approval status on :Exam|9|6,125 rows — workflow state',
'result_working_day_master' => 'Result|B|PROP|working days on :AcademicYear|9|',
'result_master_confrigration' => 'Result|D|EXCLUDE|—|—|Report config (note the typo)',
'result_template_master' => 'Result|D|EXCLUDE|—|—|Print templates',
'result_book_master'    => 'Result|D|EXCLUDE|—|—|Report-book config',
'result_trust_master'   => 'Result|D|EXCLUDE|—|—|Print header config',
'result_std_grd_maping' => 'Result|B|EDGE|(:Standard)-[:USES_GRADE_SCHEME]->(:GradeScheme)|9|',
'result_remark_masters' => 'Result|C|NODE|:RemarkTemplate|9|',
'exam_schedule'         => 'Result|B|NODE|:ExamSchedule|9|5,215 rows',
'upload_result'         => 'Result|D|EXCLUDE|—|—|Import staging log',
'MBTI_paper'            => 'Assessment|B|NODE|:Assessment|8|1 row — MBTI pilot',
'MBTI_answer'           => 'Assessment|B|PROP|answer key on :Assessment|8|**16 rows; columns are only (id, ans_key, answer_html)** — no student and no FK to MBTI_paper, so it cannot be a mastery edge',

// ───────────────────────── STAFF / HR (phase 10) ─────────────────────────
'tbluser'               => 'Staff|A|NODE|:Staff|10|4,763 rows. **PII**',
'hrms_attendances'      => 'Staff|B|AGG_EDGE|(:Staff)-[:ATTENDANCE]->(:AcademicYear)|10|**354,874 rows → ~monthly aggregate.** Date column is `day`; no syear — derive',
'hrms_emp_leaves'       => 'Staff|B|EDGE|(:Staff)-[:TOOK_LEAVE]->(:LeaveType)|10|28,406 rows',
'leave_applications'    => 'Leave|B|EDGE|(:Staff)-[:APPLIED_FOR_LEAVE]->(:LeaveType)|10|**20,396 rows — not in the master prompt.** Separate leave module',
'hrms_leave_allocation' => 'Staff|B|EDGE|(:Staff)-[:ALLOCATED]->(:LeaveType)|10|',
'hrms_leave_types'      => 'Staff|B|NODE|:LeaveType|10|',
'hrms_holidays'         => 'Staff|B|NODE|:Holiday|10|',
'hrms_departments_mapping' => 'Staff|B|EDGE|(:Staff)-[:IN_DEPARTMENT]->(:Department)|10|',
'hrms_weekdays'         => 'Staff|C|PROP|lookup|10|',
'hrms_in_out_times'     => 'Staff|D|EXCLUDE|—|—|18 rows, shift config',
'hrms_job_titles'       => 'Staff|D|EXCLUDE|—|—|Empty',
'hrms_salary_certificate' => 'Payroll|B|NODE|:SalaryCertificate|10|**authoritative=false.** 12 rows',
'hrms_emp_payroll_deduction' => 'Payroll|B|AGG_EDGE|(:Staff)-[:DEDUCTION]->(:PayrollType)|10|**authoritative=false.** 7,562 rows — no amounts as node properties',
'employee_salary_structures' => 'Payroll|B|EDGE|(:Staff)-[:HAS_SALARY_STRUCTURE]->(:PayrollType)|10|**authoritative=false.** Structure/eligibility only',
'employee_monthly_salary_data' => 'Payroll|B|AGG_EDGE|(:Staff)-[:PAYROLL_MONTH]->(:AcademicYear)|10|**authoritative=false.** 4,263 rows',
'payroll_types'         => 'Payroll|B|NODE|:PayrollType|10|**authoritative=false**',
'staff_document'        => 'Staff|B|PROP|document_count on :Staff|10|11,282 rows of file metadata',
'tblemp_skills'         => 'Staff|A|EDGE|(:Staff)-[:HAS_SKILL]->(:Skill)|13|96 rows — the only staff→skill link',
'proxy_master'          => 'Staff|B|EDGE|(:Staff)-[:SUBSTITUTED_FOR]->(:Staff)|10|6,474 rows — substitute teaching',
'mapped_teachers'       => 'Staff|B|EDGE|(:Staff)-[:MAPPED_TO]->(:Subject)|10|**Only 11 rows** — verify before relying on it',
'timetable'             => 'Timetable|B|EDGE|(:Staff)-[:TEACHES]->(:Subject) + (:Division)-[:SCHEDULED]->(:Subject)|10|102,652 rows. Full tenancy + teacher_id/subject_id/period_id/division_id',
'create_timetable'      => 'Timetable|D|EXCLUDE|—|—|54 rows, generator config',
'college_timetable'     => 'Timetable|D|EXCLUDE|—|—|Empty',
'tbluser_contact_details' => 'Staff|B|PROP|on :Staff|10|',
'tbluser_past_education' => 'Staff|D|EXCLUDE|—|—|Empty',
'tbluser_shift_master'  => 'Staff|B|NODE|:Shift|10|3 rows',
'tbluser_shift_records' => 'Staff|D|EXCLUDE|—|—|Empty',
'role_responsibility'   => 'Staff|B|PROP|on :Role|10|',
'biomatrix'             => 'Staff|D|EXCLUDE|—|—|Empty biometric config',
'users'                 => 'Platform|D|EXCLUDE|—|—|Laravel auth table, 1 row',
'password_resets'       => 'Platform|D|EXCLUDE|—|—|Framework table',
'personal_access_tokens' => 'Platform|D|EXCLUDE|—|—|Framework table',
'tblgroupwise_rights'   => 'Platform|D|EXCLUDE|—|—|30,557-row permission matrix — no traversal value',
'tblindividual_rights'  => 'Platform|D|EXCLUDE|—|—|25,060-row permission matrix',
'tblprofilewise_menu'   => 'Platform|D|EXCLUDE|—|—|48,351-row menu matrix',
'tblmenumaster'         => 'Platform|D|EXCLUDE|—|—|Menu definitions',
'tblmenumaster_new'     => 'Platform|D|EXCLUDE|—|—|Empty',
'tblmenumaster_old'     => 'Platform|D|EXCLUDE|—|—|Empty',
'hp_tblmenumaster'      => 'Platform|D|EXCLUDE|—|—|Menu definitions, 0 refs',
'rightside_menumaster'  => 'Platform|D|EXCLUDE|—|—|Menu definitions',
'new_client_rights'     => 'Platform|D|EXCLUDE|—|—|Permission config',

// ───────────────────────── FINANCE (phase 11) ─────────────────────────
'fees_head_master'      => 'Fees|B|NODE|:FeeHead|11|**authoritative=false**',
'fees_title'            => 'Fees|B|NODE|:FeeTitle|11|**authoritative=false.** q210',
'fees_title_master'     => 'Fees|B|NODE|:FeeTitleMaster|11|**authoritative=false**',
'fees_config_master'    => 'Fees|B|NODE|:FeeConfig|11|**authoritative=false**',
'fees_late_master'      => 'Fees|B|NODE|:LateFeeRule|11|**authoritative=false**',
'fees_month_header'     => 'Fees|B|NODE|:FeeMonth|11|**authoritative=false**',
'fees_circular_master'  => 'Fees|B|NODE|:FeeCircular|11|**authoritative=false**',
'fees_other_head'       => 'Fees|B|NODE|:FeeOtherHead|11|**authoritative=false.** **Split from :FeeHead 2026-08-10** — 2 (tenant,pk) pairs collide with fees_head_master',
'fees_cancel_type'      => 'Fees|B|NODE|:FeeCancelType|11|**authoritative=false**',
'bank_master'           => 'Fees|B|NODE|:Bank|11|**authoritative=false**',
'fees_breackoff'        => 'Fees|B|AGG_EDGE|(:FeeSchedule)-[:APPLIES_TO]->(:Standard)|11|**182,333 rows and NO student_id.** It is a fee *schedule* per (grade,standard,quota,month), not a student ledger. Master prompt was wrong — see F5',
'fees_breakoff_other'   => 'Fees|B|AGG_EDGE|(:Student)-[:LIABLE_FOR]->(:FeeHead)|11|46,861 rows — **this one does have student_id**. authoritative=false',
'fees_collect'          => 'Fees|B|AGG_EDGE|(:Student)-[:PAID]->(:FeeTitle)|11|**Only 13 rows** despite q112. The collection ledger is effectively empty here — see F6',
'fees_receipt_book_master' => 'Fees|B|NODE|:ReceiptBook|11|9,734 rows — receipt *stationery* config, not receipts. No student_id',
'fees_cancel'           => 'Fees|B|PROP|status on the LIABLE_FOR edge|11|7,837 rows',
'fees_other_cancel'     => 'Fees|B|PROP|status|11|',
'fees_other_collection' => 'Fees|B|AGG_EDGE|(:Student)-[:PAID]->(:FeeHead)|11|2,098 rows. authoritative=false',
'fees_paid_other'       => 'Fees|B|AGG_EDGE|(:Student)-[:PAID]->(:FeeHead)|11|21 rows',
'fees_refund'           => 'Fees|B|PROP|refund flag|11|6 rows',
'fees_map_years'        => 'Fees|B|EDGE|(:FeeConfig)-[:FOR_YEAR]->(:AcademicYear)|11|',
'fees_reconciliation'   => 'Fees|D|EXCLUDE|—|—|**Never project.** Reconciliation must not have a second copy (6,721 rows)',
'fees_breackoff_logs'   => 'Fees|D|EXCLUDE|—|—|Audit log',
'fees_circular_log'     => 'Fees|D|EXCLUDE|—|—|Audit log',
'fees_payment'          => 'Fees|D|EXCLUDE|—|—|**0 rows but 60 code refs** — see F7',
'fees_online_split'     => 'Fees|D|EXCLUDE|—|—|Empty',
'fees_online_maping'    => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_aggre_pay'        => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_axis'             => 'Fees|D|EXCLUDE|—|—|Gateway config, empty',
'fees_hdfcrazorpay'     => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_hdffc'            => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_icici'            => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_payphi'           => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_razorpay'         => 'Fees|D|EXCLUDE|—|—|Gateway config',
'fees_receipt'          => 'Fees|D|EXCLUDE|—|—|22 rows, print config',
'fees_receipt_css'      => 'Fees|D|EXCLUDE|—|—|Stylesheet config',
'imprest_fees_cancel'   => 'Fees|D|EXCLUDE|—|—|107 rows, cancellation log',
'petty_cash'            => 'Fees|B|AGG_EDGE|(:Staff)-[:PETTY_CASH]->(:AcademicYear)|11|**authoritative=false**',
'petty_cash_master'     => 'Fees|B|NODE|:PettyCashHead|11|**authoritative=false**',
'donation_collection'   => 'Fees|B|AGG_EDGE|(:Institute)-[:RECEIVED_DONATION]->(:AcademicYear)|11|**authoritative=false**',
'NACH_MASTER'           => 'Fees|D|EXCLUDE|—|—|Mandate config',
'NACH_ac_type'          => 'Fees|D|EXCLUDE|—|—|Lookup',

// ───────────────────────── OPERATIONS (phase 12) ─────────────────────────
'library_books'         => 'Library|B|NODE|:Book|12|35,663 rows. Uses `academic_year`, not syear',
'library_items'         => 'Library|B|EDGE|(:BookCopy)-[:COPY_OF]->(:Book)|12|36,181 physical copies',
'library_book_circulations' => 'Library|B|AGG_EDGE|(:Student)-[:BORROWED]->(:Book)|12|**67,487 rows → aggregate per (student, book).** Enables "students who read X also read Y"',
'transport_route'       => 'Transport|B|NODE|:Route|12|',
'transport_stop'        => 'Transport|B|NODE|:Stop|12|',
'transport_vehicle'     => 'Transport|B|NODE|:Vehicle|12|',
'transport_driver_detail' => 'Transport|B|NODE|:Driver|12|**PII**',
'transport_school_shift' => 'Transport|B|NODE|:Shift|12|',
'transport_vehicle_type' => 'Transport|C|NODE|:VehicleType|12|',
'transport_route_stop'  => 'Transport|B|EDGE|(:Route)-[:HAS_STOP {sequence}]->(:Stop)|12|',
'transport_route_bus'   => 'Transport|B|EDGE|(:Vehicle)-[:SERVES]->(:Route)|12|',
'transport_map_student' => 'Transport|B|EDGE|(:Student)-[:BOARDS_AT]->(:Stop)|12|30,300 rows. **Two edges per row** — from_stop and to_stop',
'transport_kilometer_rate' => 'Transport|B|PROP|rate on :Route|12|',
'hostel_master'         => 'Hostel|B|NODE|:Hostel|12|',
'hostel_building_master' => 'Hostel|B|NODE|:HostelBuilding|12|',
'hostel_floor_master'   => 'Hostel|B|NODE|:HostelFloor|12|',
'hostel_room_master'    => 'Hostel|B|NODE|:HostelRoom|12|',
'hostel_type_master'    => 'Hostel|C|NODE|:HostelType|12|',
'hostel_room_allocation' => 'Hostel|B|EDGE|(:Student)-[:ALLOCATED_ROOM]->(:HostelRoom)|12|Only 9 rows',
'hostel_visitor_master' => 'Hostel|B|EDGE|(:Visitor)-[:VISITED]->(:Student)|12|5 rows',
'inventory_item_master' => 'Inventory|B|NODE|:InventoryItem|12|',
'inventory_item_category_master' => 'Inventory|B|NODE|:ItemCategory|12|',
'inventory_item_sub_category_master' => 'Inventory|B|NODE|:ItemSubCategory|12|',
'inventory_vendor_master' => 'Inventory|B|NODE|:Vendor|12|',
'inventory_item_type'   => 'Inventory|C|NODE|:ItemType|12|',
'inventory_requisition_details' => 'Inventory|B|EDGE|(:Staff)-[:REQUISITIONED]->(:InventoryItem)|12|',
'inventory_allocation_details' => 'Inventory|B|EDGE|(:Staff)-[:ALLOCATED_ITEM]->(:InventoryItem)|12|Uses UPPERCASE SUB_INSTITUTE_ID',
'inventory_item_direct_purchase' => 'Inventory|B|EDGE|(:Vendor)-[:SUPPLIED]->(:InventoryItem)|12|',
'inventory_generate_po_details' => 'Inventory|B|EDGE|(:Vendor)-[:PURCHASE_ORDER]->(:InventoryItem)|12|',
'inventory_item_quotation_details' => 'Inventory|B|EDGE|(:Vendor)-[:QUOTED]->(:InventoryItem)|12|',
'inventory_negotiate_po_details' => 'Inventory|D|EXCLUDE|—|—|4 rows, workflow detail',
'inventory_item_receivable_details' => 'Inventory|D|EXCLUDE|—|—|4 rows',
'inventory_item_defective_details' => 'Inventory|D|EXCLUDE|—|—|Empty',
'inventory_item_lost_details' => 'Inventory|D|EXCLUDE|—|—|Empty',
'inventory_item_return_details' => 'Inventory|D|EXCLUDE|—|—|Empty',
'inventory_requisition_status_master' => 'Inventory|C|PROP|status lookup|12|',
'inventory_master_setup' => 'Inventory|D|EXCLUDE|—|—|Config',
'inventory_tax_master'  => 'Inventory|D|EXCLUDE|—|—|Tax config',
'item_scan_details'     => 'Inventory|D|EXCLUDE|—|—|**32,569-row scan log.** Aggregate a scan_count property only',
'physical_file_location' => 'Operations|B|NODE|:FileLocation|12|',
'visitor_master'        => 'Visitor|B|NODE|:Visitor|12|**PII**',
'visitor_type'          => 'Visitor|B|NODE|:VisitorType|12|',
'visitor_master_settings' => 'Visitor|D|EXCLUDE|—|—|Config',
'inward'                => 'Operations|B|NODE|:InwardDocument|12|5,773 rows',
'outward'               => 'Operations|B|NODE|:OutwardDocument|12|149 rows',
'front_desk'            => 'FrontDesk|B|NODE|:FrontDeskEntry|12|1 row. Uses UPPERCASE SUB_INSTITUTE_ID',
'complaint'             => 'FrontDesk|B|NODE|:Complaint|12|Uses UPPERCASE SUB_INSTITUTE_ID',
'complaint_status'      => 'FrontDesk|C|PROP|status lookup|12|',
'follow_up'             => 'FrontDesk|D|EXCLUDE|—|—|4 rows',
'circular'              => 'FrontDesk|B|NODE|:Circular|12|1 row, q34',
'circular_type'         => 'FrontDesk|C|NODE|:CircularType|12|',
'announcement'          => 'FrontDesk|B|NODE|:Announcement|12|',
'house_master_dummy'    => 'Foundation|D|EXCLUDE|—|—|',

// ───────────────────────── SKILL / CAREER (phase 13) ─────────────────────────
'master_skills'         => 'Skill|A|NODE|:Skill|13|16,239 rows. sub_institute_id = 0 → reference data, not tenant-scoped',
's_jobrole'             => 'Skill|A|NODE|:JobRole|13|5,805 rows',
's_jobrole_skills'      => 'Skill|A|EDGE|(:JobRole)-[:REQUIRES_SKILL]->(:Skill)|13|**176,460 rows. `jobrole` and `skill` are NAME STRINGS, not ids** — violates L1. See F8',
's_jobrole_task'        => 'Skill|A|EDGE|(:JobRole)-[:INVOLVES_TASK]->(:Task)|13|34,060 rows',
's_assessment_library'  => 'Skill|A|NODE|:SkillAssessment|13|40 rows',
's_skill_matrix'        => 'Skill|A|EDGE|(:Staff)-[:HAS_SKILL]->(:Skill)|13|**Only 3 rows.** `user_id` → tbluser',
's_user_jobrole'        => 'Skill|A|EDGE|(:Staff)-[:TARGETS_JOBROLE]->(:JobRole)|13|4,909 rows',
's_industries'          => 'Skill|C|NODE|:Industry|13|715 rows, 0 code refs',
's_skill_map_k_a'       => 'Skill|D|EXCLUDE|—|—|**138,461 rows / 79.7 MB, 0 code references.** Do not project — confirm with owner first',
'sqaa_master'           => 'SQAA|B|NODE|:SQAAStandard|13|',
'sqaa_documant_master'  => 'SQAA|B|NODE|:SQAADocument|13|1,534 rows (note the typo)',
'sqaa_documents'        => 'SQAA|B|EDGE|(:Institute)-[:SUBMITTED]->(:SQAADocument)|13|',
'sqaa_marks'            => 'SQAA|B|EDGE|(:Institute)-[:SCORED_SQAA]->(:SQAAStandard)|13|6 rows',

// ───────────────────────── PLATFORM / MISC (phase 14) ─────────────────────────
'ptm_booking_master'    => 'PTM|B|EDGE|(:Guardian)-[:BOOKED]->(:Staff)|14|789 rows',
'ptm_time_slots_master' => 'PTM|B|NODE|:TimeSlot|14|',
'calendar_events'       => 'Calendar|B|NODE|:CalendarEvent|14|3,941 rows',
'erptour'               => 'Platform|D|EXCLUDE|—|—|UI tour state',
'sms_sent_parents'      => 'Communication|B|AGG_EDGE|(:Student)-[:COMMUNICATION]->(:AcademicYear)|14|**53,447-row send log** — aggregate counts only',
'sms_sent_staff'        => 'Communication|B|AGG_EDGE|(:Staff)-[:COMMUNICATION]->(:AcademicYear)|14|10 rows',
'email_sent_parents'    => 'Communication|B|AGG_EDGE|(:Staff)-[:COMMUNICATION]->(:AcademicYear)|14|2,761 rows. Keys on USER_ID (staff sender); there is no student_id, so this cannot hang off :Student',
'whatsapp_sent_messages' => 'Communication|B|AGG_EDGE|(:Student)-[:COMMUNICATION]->(:AcademicYear)|14|11,153 rows',
'parent_communication'  => 'Communication|B|AGG_EDGE|(:Student)-[:COMMUNICATION]->(:AcademicYear)|14|22,729 rows',
'incoming_messages'     => 'Communication|D|EXCLUDE|—|—|Inbound webhook log',
'sms_api_details'       => 'Communication|D|EXCLUDE|—|—|Gateway config',
'whatapp_user_details'  => 'Communication|D|EXCLUDE|—|—|Gateway config (note the typo)',
'smtp_details'          => 'Communication|D|EXCLUDE|—|—|Mail config',
'gcm_users'             => 'Communication|D|EXCLUDE|—|—|**26,199-row push-token registry** — no traversal value',
'app_notification'      => 'Communication|D|EXCLUDE|—|—|Notification log',
'app_notification_teacher' => 'Communication|D|EXCLUDE|—|—|Empty',
'app_language'          => 'Platform|D|EXCLUDE|—|—|i18n strings',
'mobile_homescreen'     => 'Platform|D|EXCLUDE|—|—|UI config',
'teacher_mobile_homescreen' => 'Platform|D|EXCLUDE|—|—|UI config',
'dynamic_dashboard'     => 'Platform|D|EXCLUDE|—|—|UI config',
'dashboard_master'      => 'Platform|D|EXCLUDE|—|—|Empty',
'photo_video_gallary'   => 'Platform|D|EXCLUDE|—|—|Empty (note the typo)',
'task'                  => 'Platform|B|NODE|:Task|14|887 rows, q51',
'task_management_comments' => 'Platform|D|EXCLUDE|—|—|Empty',
'task_management_dependencies' => 'Platform|D|EXCLUDE|—|—|Empty',
'task_management_milestones' => 'Platform|D|EXCLUDE|—|—|Empty',
'blogs'                 => 'Platform|D|EXCLUDE|—|—|11 rows, CMS content',
'form_builder'          => 'Platform|D|EXCLUDE|—|—|Form metadata',
'form_submit_data'      => 'Platform|D|EXCLUDE|—|—|Form submissions',
'report_dynamic'        => 'Report|D|EXCLUDE|—|—|Report definitions — read path only',
'report_module'         => 'Report|D|EXCLUDE|—|—|Report definitions',
'report_module_data'    => 'Report|D|EXCLUDE|—|—|Report definitions',
'report_module_fields'  => 'Report|D|EXCLUDE|—|—|Report definitions',
'custom_module_tables'  => 'Platform|D|EXCLUDE|—|—|Dynamic-table metadata',
'custom_module_table_columns' => 'Platform|D|EXCLUDE|—|—|Dynamic-table metadata',
'import_table_fields'   => 'Platform|D|EXCLUDE|—|—|Import mapping config',
'relation_table_fields' => 'Platform|D|EXCLUDE|—|—|Import mapping config',
'table_relation'        => 'Platform|D|EXCLUDE|—|—|Import mapping config',
'csv_data'              => 'Platform|D|EXCLUDE|—|—|Import staging',
'tblcustom_fields'      => 'Platform|D|EXCLUDE|—|—|Custom-field metadata',
'tblfields_data'        => 'Platform|D|EXCLUDE|—|—|Custom-field metadata',
'onboarding_module'     => 'Platform|D|EXCLUDE|—|—|Onboarding checklist',
'onboarding_progress'   => 'Platform|D|EXCLUDE|—|—|Onboarding checklist',
'onboarding_step'       => 'Platform|D|EXCLUDE|—|—|Onboarding checklist',
'document_templates'    => 'Platform|D|EXCLUDE|—|—|Empty',
'document_template_versions' => 'Platform|D|EXCLUDE|—|—|Empty',
'implementation_master' => 'Platform|D|EXCLUDE|—|—|Empty',
'requirement_gathering' => 'Platform|D|EXCLUDE|—|—|5 rows',
'knowledge_base_dummy'  => 'Platform|D|EXCLUDE|—|—|',
'recommendations'       => 'Platform|D|EXCLUDE|—|—|**0 rows but 11 code refs** — see F7',
'ai_api_keys'           => 'Platform|D|EXCLUDE|—|—|Secrets',
'ai_daily_used_api'     => 'Platform|D|EXCLUDE|—|—|Usage counter',
'ai_interaction_logs'   => 'Platform|D|EXCLUDE|—|—|LLM call log',
'ai_sops'               => 'Platform|D|EXCLUDE|—|—|Prompt config',
'api_details'           => 'Platform|D|EXCLUDE|—|—|Config',
'application_forms'     => 'Platform|D|EXCLUDE|—|—|Empty',
'tblapplications'       => 'Platform|D|EXCLUDE|—|—|Empty',
'migrations'            => 'Platform|D|EXCLUDE|—|—|Laravel framework table',
'access_log'            => 'Platform|D|EXCLUDE|—|—|Audit log (empty)',
'access_log_route'      => 'Platform|D|EXCLUDE|—|—|Audit log',
'activity_log'          => 'Platform|D|EXCLUDE|—|—|Audit log (empty)',
'ERR_LOG'               => 'Platform|D|EXCLUDE|—|—|Error log',
'S2_LOG'                => 'Platform|D|EXCLUDE|—|—|Integration log',
'sync_log'              => 'Platform|D|EXCLUDE|—|—|9,240 rows, 0 code refs',
'neo4j_sync_queue'      => 'Platform|D|EXCLUDE|—|—|**12,193 rows, 0 code references.** Orphaned queue from a previous sync attempt — see F10',
'sharebazar_margin'     => 'NotK12|D|EXCLUDE|—|—|Stock-trading module — not K12. Confirm before deleting',
'sharebazar_pnl'        => 'NotK12|D|EXCLUDE|—|—|Stock-trading module — not K12',
'sharebazar_position'   => 'NotK12|D|EXCLUDE|—|—|**77,305 rows.** Stock-trading module — not K12',
'Z_customer_registrations' => 'NotK12|D|EXCLUDE|—|—|Prefixed-Z scratch table, 0 refs',
'Z_donarDetails'        => 'NotK12|D|EXCLUDE|—|—|Prefixed-Z scratch table',
'Z_employee_details'    => 'NotK12|D|EXCLUDE|—|—|Prefixed-Z scratch table, empty',
'Z_Seminar'             => 'NotK12|D|EXCLUDE|—|—|Prefixed-Z scratch table',
'Z_Student_Details'     => 'NotK12|D|EXCLUDE|—|—|Prefixed-Z scratch table',

// ───────────────────────── LEADERBOARD / REMAINDER ─────────────────────────
'lb_master'             => 'Leaderboard|B|NODE|:LeaderboardRule|14|5 rows — points rule per (grade, standard, module)',
'lb_points'             => 'Leaderboard|B|AGG_EDGE|(:Staff)-[:EARNED_POINTS]->(:LeaderboardRule)|14|2 rows. `user_id` → tbluser, not tblstudent',
'master_compliance'     => 'Platform|D|EXCLUDE|—|—|Empty compliance tracker',
'onet_institute_data'   => 'ONET|C|REVIEW|—|13|**65,738 rows of Indian college listings (AICTE).** Not K12 and not occupation data — decide whether the careers module needs it',
'user_activities'       => 'Platform|B|EDGE|(:Staff)-[:VIEWED]->(:Content)|14|24 rows — content view log',
'user_experience_details' => 'Staff|D|EXCLUDE|—|—|Empty prior-employment table',
];
