<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The prompts, report layout and example policy for Exam & Assessment — mirroring
 * 2026_09_22_100100 (Exam, PTM, Hostel, Student Request, Circular) and
 * 2026_09_22_100400 (the example-policy-per-module migration), for one module rather
 * than several.
 *
 * TWO PROSE PROMPTS AND ONE REPORT, GROUNDED ON THE SAME TOOL THE AGENT USES
 *
 * `data_source = 'exam_assessment.online_exam_summary'` is the same tool
 * `OnlineExamLowScoreDetector` reads — the report and a question asked on the page are
 * answered from the same figures the agent's cases are opened from.
 *
 * EVERY PLACEHOLDER IS A FIELD THE TOOL REALLY RETURNS
 *
 * Taken from `OnlineExamReportService::summary()` itself: the `at_risk_attempts` rows
 * carry `student_name, paper_name, obtain_marks, total_marks, percent, attempted_at`, and
 * the top-level scalars carry `exams_published, attempts_recorded, students_assessed,
 * average_score, needs_attention, at_risk_percent`. `AiReportGenerator::rowsOf()` finds
 * `at_risk_attempts` automatically as the largest list of row-shaped arrays in the
 * payload; no key name has to match anything.
 *
 * WHAT THIS MODULE MUST REFUSE TO SAY
 *
 * An online exam attempt is one performance on one day, not a verdict on a child, and a
 * PAL-generated paper is not a teacher's own exam — the same two refusals the Exam module
 * and New PAL modules already carry, applied here for the same reason.
 *
 * FEES, ATTENDANCE, EXAM, NEW PAL AND EVERY OTHER MODULE ARE NOT TOUCHED. Every write is
 * keyed on a template key beginning `k12.exam_assessment.` or a policy name unique to
 * this module.
 */
return new class extends Migration
{
    private const MODULE_KEY = 'exam_assessment';

    public function up(): void
    {
        $this->publishTemplates();
        $this->bindSuggestions();
        $this->seedExamplePolicy();
    }

    public function down(): void
    {
        if (Schema::hasTable('ai_templates')) {
            DB::table('ai_templates')
                ->whereIn('template_key', array_column($this->templateRows(), 'template_key'))
                ->whereNull('sub_institute_id')
                ->update(['status' => 'retired', 'updated_at' => now()]);
        }

        if (Schema::hasTable('ai_suggestions')) {
            DB::table('ai_suggestions')
                ->where('module_key', self::MODULE_KEY)
                ->where('capability', 'generative')
                ->whereNull('sub_institute_id')
                ->delete();
        }

        if (Schema::hasTable('ai_policies')) {
            $ids = DB::table('ai_policies')
                ->where('name', $this->policy()['name'])
                ->whereNull('sub_institute_id')
                ->where('is_example', 1)
                ->pluck('id');

            if ($ids->isNotEmpty()) {
                foreach (['ai_policy_rules', 'ai_policy_assignments'] as $table) {
                    if (Schema::hasTable($table)) {
                        DB::table($table)->whereIn('policy_id', $ids)->delete();
                    }
                }

                DB::table('ai_policies')->whereIn('id', $ids)->delete();
            }
        }
    }

    // ------------------------------------------------------------------ templates

    private function publishTemplates(): void
    {
        if (! Schema::hasTable('ai_templates') || ! Schema::hasColumn('ai_templates', 'kind')) {
            return;
        }

        foreach ($this->templateRows() as $template) {
            $existing = DB::table('ai_templates')
                ->where('template_key', $template['template_key'])
                ->whereNull('sub_institute_id')
                ->first();

            if ($existing !== null) {
                DB::table('ai_templates')->where('id', $existing->id)->update($template + ['updated_at' => now()]);

                continue;
            }

            DB::table('ai_templates')->insert($template + ['created_at' => now(), 'updated_at' => now()]);
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function templateRows(): array
    {
        $refusals = [
            'Do not invent an exam, a subject, a class, a mark, a percentage or a count.',
            'An online exam attempt is one performance on one day. Never characterise a student as able, weak, lazy or gifted from it.',
            'A paper generated by the PAL engine is not a teacher-published exam; do not fold the two together in a summary.',
            'Do not compare against a previous term or year unless those records were provided.',
        ];
        $rules = json_encode($refusals);

        $cover = "1. Which exams and subjects the recorded attempts cover, and for which classes.\n"
            . "2. What the average score is, and how many attempts fall below the bar.\n"
            . "3. Whether the rows shown are the whole set or a sample of a larger one.\n";

        $analysisCover = "1. Which subjects or classes the recorded attempts are strongest and weakest in.\n"
            . "2. How many attempts fall below the bar, and what that means for the class.\n"
            . "3. What the records do not contain that would be needed to say more.\n"
            . "4. One or two concrete next steps a subject teacher could take.\n";

        $variables = json_encode([
            ['key' => 'records', 'label' => 'Online exam attempt records', 'required' => true, 'type' => 'text', 'grounding' => true],
            ['key' => 'metrics', 'label' => 'Exam & Assessment figures', 'required' => false, 'type' => 'text', 'grounding' => true],
            ['key' => 'page_title', 'label' => 'Page title', 'required' => false, 'type' => 'string'],
            ['key' => 'filters', 'label' => 'Filters', 'required' => false, 'type' => 'string'],
            ['key' => 'search_query', 'label' => 'Search', 'required' => false, 'type' => 'string'],
            ['key' => 'record_count', 'label' => 'Total records', 'required' => false, 'type' => 'string'],
            ['key' => 'rows_shown', 'label' => 'Rows shown', 'required' => false, 'type' => 'string'],
            ['key' => 'is_partial', 'label' => 'Partial view', 'required' => false, 'type' => 'string'],
        ]);

        $systemRole = 'You summarise recorded online exam attempts for a subject teacher.';

        return [
            [
                'template_key' => 'k12.exam_assessment.summary',
                'name' => 'Exam & Assessment summary',
                'description' => 'A short summary of the online exam attempts on the screen.',
                'module_key' => self::MODULE_KEY,
                'domain' => 'k12',
                'category' => 'report',
                'kind' => 'prompt',
                'version' => 1,
                'status' => 'published',
                'output_format' => 'text',
                'system_prompt' => $systemRole.' Work only from the records given below. Never state a name, a date, a figure or a count that is not in them, and never estimate one. '.implode(' ', $refusals),
                'user_prompt' => "Summarise the online exam attempts on this page.\n\n"
                    . "Page: {{page_title}}\nActive filters: {{filters}}\nSearch: {{search_query}}\n"
                    . "Figures on screen: {{metrics}}\nRecords shown: {{rows_shown}} of {{record_count}} (partial view: {{is_partial}})\n"
                    . "Rows:\n{{records}}\n\nCover:\n".$cover
                    . "\nIf no online exam records were reported, say that none were provided rather than describing the module as empty.",
                'variables' => $variables,
                'safety_rules' => $rules,
                'requires_review' => 0,
                'allow_as_evidence' => 0,
                'sub_institute_id' => null,
                'client_id' => null,
            ],
            [
                'template_key' => 'k12.exam_assessment.analysis',
                'name' => 'Exam & Assessment analysis',
                'description' => 'What the online exam attempts show, and what the records do not support saying.',
                'module_key' => self::MODULE_KEY,
                'domain' => 'k12',
                'category' => 'report',
                'kind' => 'prompt',
                'version' => 1,
                'status' => 'published',
                'output_format' => 'text',
                'system_prompt' => $systemRole.' Work only from the records given below. Never state a name, a date, a figure or a count that is not in them, and never estimate one. '.implode(' ', $refusals),
                'user_prompt' => "Analyse the online exam attempts in these records.\n\n"
                    . "Page: {{page_title}}\nActive filters: {{filters}}\nSearch: {{search_query}}\n"
                    . "Figures on screen: {{metrics}}\nRecords shown: {{rows_shown}} of {{record_count}} (partial view: {{is_partial}})\n"
                    . "Rows:\n{{records}}\n\nCover:\n".$analysisCover
                    . "\nIf no online exam records were reported, say that none were provided rather than describing the module as empty.",
                'variables' => $variables,
                'safety_rules' => $rules,
                'requires_review' => 0,
                'allow_as_evidence' => 0,
                'sub_institute_id' => null,
                'client_id' => null,
            ],
            [
                'template_key' => 'k12.exam_assessment.report',
                'name' => 'Online Exam Results Report',
                'description' => 'The online exam attempts below the bar for this institute, with the exam, score and student each belongs to.',
                'module_key' => self::MODULE_KEY,
                'domain' => 'k12',
                'category' => 'report',
                'kind' => 'report',
                'version' => 1,
                'status' => 'published',
                'user_prompt' => '',
                'html_layout' => $this->layout(),
                'data_source' => 'exam_assessment.online_exam_summary',
                'data_arguments' => json_encode(['limit' => 100]),
                'output_format' => 'text',
                'requires_review' => 0,
                'allow_as_evidence' => 0,
                'sub_institute_id' => null,
                'client_id' => null,
            ],
        ];
    }

    private function layout(): string
    {
        $cell = 'style="border:1px solid #cbd5e1;padding:6px;text-align:left"';
        $columns = [
            ['Student', 'student_name'],
            ['Exam', 'paper_name'],
            ['Marks', 'obtain_marks'],
            ['Out of', 'total_marks'],
            ['Percent', 'percent'],
            ['Attempted on', 'attempted_at'],
        ];

        $headings = '<th style="border:1px solid #cbd5e1;padding:6px;text-align:left;width:36px">#</th>';
        $cells = '<td '.$cell.'><<row_number>></td>';

        foreach ($columns as [$heading, $field]) {
            $headings .= "\n        <th ".$cell.'>'.$heading.'</th>';
            $cells .= "\n        <td ".$cell.'><<'.$field.'>></td>';
        }

        return <<<HTML
<div style="font-family:Segoe UI,Arial,sans-serif;color:#0f172a">

  <h2 style="margin:0 0 4px 0;font-size:20px"><<report_title>></h2>
  <p style="margin:0 0 16px 0;color:#475569;font-size:13px">
    <<row_count>> row(s) listed &middot; academic year <<academic_year>> &middot; generated <<generated_at>>
  </p>

  <table style="width:100%;border-collapse:collapse;font-size:13px">
    <thead>
      <tr style="background:#f1f5f9">
        {$headings}
      </tr>
    </thead>
    <tbody>
      <<#rows>>
      <tr>
        {$cells}
      </tr>
      <</rows>>
    </tbody>
  </table>

  <p style="margin:16px 0 0 0;font-size:13px">
    <strong>Exams published: <<exams_published>> &mdash; attempts recorded: <<attempts_recorded>> &mdash; average score: <<average_score>>% &mdash; below the <<at_risk_percent>>% bar: <<needs_attention>>.</strong>
  </p>
  <p style="margin:6px 0 0 0;color:#475569;font-size:12px">
    Papers generated by the PAL engine are excluded. A blank cell is a detail the school has not recorded, not a detail that does not exist.
  </p>

</div>
HTML;
    }

    // ------------------------------------------------------------------ suggestions

    private function bindSuggestions(): void
    {
        if (! Schema::hasTable('ai_suggestions')) {
            return;
        }

        $rows = [
            ['generate', 'k12.exam_assessment.summary', 'Summarise online exam attempts', 'Summarise the online exam attempts on this page from the records themselves.'],
            ['generate', 'k12.exam_assessment.analysis', 'Analyse online exam attempts', 'What the online exam attempts show, and what the records do not support saying.'],
            ['report', null, 'Online Exam Results Report', 'Build the online exam results report document from the attempt records.'],
        ];

        foreach ($rows as $index => [$actionType, $ref, $label, $description]) {
            $exists = DB::table('ai_suggestions')
                ->where('module_key', self::MODULE_KEY)
                ->where('capability', 'generative')
                ->where('label', $label)
                ->whereNull('sub_institute_id')
                ->exists();

            if ($exists) {
                continue;
            }

            DB::table('ai_suggestions')->insert([
                'module_key' => self::MODULE_KEY,
                'capability' => 'generative',
                'label' => $label,
                'description' => $description,
                'icon' => null,
                'action_type' => $actionType,
                'action_ref' => $ref,
                'prompt' => null,
                'payload' => null,
                'requires_entity' => 0,
                'allowed_roles' => null,
                'required_permissions' => null,
                'sort_order' => ($index + 1) * 10,
                'status' => 1,
                'sub_institute_id' => null,
                'client_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    // ------------------------------------------------------------------ policy

    /**
     * @return array<string, mixed>
     */
    private function policy(): array
    {
        return [
            'name' => 'Exam & Assessment interpretation policy',
            'type' => 'ai_assisted',
            'description' => 'AI may summarise recorded online exam attempts and explain what a set of results '
                . 'does and does not show. A PAL-generated paper is not a teacher-published exam and must never '
                . 'be folded into a teacher\'s own results. An attempt records one performance on one day, so AI '
                . 'may never characterise a student as able, weak, lazy or gifted from it.',
            'disclosure' => 1,
            'acknowledgement' => 1,
            'overrides' => ['use_ai_for_generating_answers' => false, 'use_ai_for_completing_assignments' => false],
        ];
    }

    private const PERMISSIVE_BASELINE = [
        'use_ai_for_brainstorming' => true,
        'use_ai_for_grammar_spelling' => true,
        'use_ai_for_explanations' => true,
        'use_ai_for_summarization' => true,
        'use_ai_for_rewriting' => true,
        'use_ai_for_generating_answers' => false,
        'use_ai_for_generating_code' => false,
        'use_ai_for_generating_images' => false,
        'use_ai_for_completing_assignments' => false,
    ];

    private function seedExamplePolicy(): void
    {
        if (! Schema::hasTable('ai_policies')
            || ! Schema::hasTable('ai_policy_rules')
            || ! Schema::hasTable('ai_policy_assignments')
            || ! Schema::hasTable('ai_modules')) {
            return;
        }

        $policy = $this->policy();

        $moduleId = DB::table('ai_modules')
            ->where('module_key', self::MODULE_KEY)
            ->whereNull('sub_institute_id')
            ->where('status', 1)
            ->value('id');

        if ($moduleId === null) {
            return;
        }

        $existing = DB::table('ai_policies')
            ->where('name', $policy['name'])
            ->whereNull('sub_institute_id')
            ->where('is_example', 1)
            ->value('id');

        if ($existing !== null) {
            return;
        }

        $policyId = DB::table('ai_policies')->insertGetId([
            'sub_institute_id' => null,
            'name' => $policy['name'],
            'description' => $policy['description'],
            'policy_type' => $policy['type'],
            'is_example' => 1,
            'status' => 1,
            'require_disclosure' => $policy['disclosure'],
            'require_acknowledgement' => $policy['acknowledgement'],
            'ai_detection_required' => 0,
            'plagiarism_check_required' => 0,
            'detection_provider' => null,
            'detection_threshold' => null,
            'created_by' => null,
            'updated_by' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        foreach (array_merge(self::PERMISSIVE_BASELINE, $policy['overrides']) as $rule => $enabled) {
            DB::table('ai_policy_rules')->insert([
                'policy_id' => $policyId,
                'rule_key' => $rule,
                'rule_value' => $enabled ? 1 : 0,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::table('ai_policy_assignments')->insert([
            'policy_id' => $policyId,
            'scope_type' => 'module',
            'scope_id' => $moduleId,
            'sub_institute_id' => null,
            'status' => 1,
            'created_by' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
};
