<?php

return [
    'pedagogies' => [
        'inquiry_based' => [
            'label' => 'Inquiry Based',
            'description' => 'Question-led exploration for new ideas and investigations.',
            'primary_h5p' => ['interactive_video', 'course_presentation', 'essay', 'questionnaire'],
        ],
        'experiential' => [
            'label' => 'Experiential',
            'description' => 'Learning through real-world activity, reflection, and application.',
            'primary_h5p' => ['documentation_tool', 'image_sequencing'],
        ],
        'art_integrated' => [
            'label' => 'Art Integrated',
            'description' => 'Concept learning through visual, performing, and creative arts.',
            'primary_h5p' => ['image_hotspot', 'audio_recorder', 'interactive_video'],
        ],
        'game_based' => [
            'label' => 'Game Based',
            'description' => 'Motivation and feedback through game mechanics and challenge.',
            'primary_h5p' => ['memory_game', 'crossword', 'agamotto', 'drag_and_drop'],
        ],
        'activity_based' => [
            'label' => 'Activity Based',
            'description' => 'Hands-on concept building through concrete tasks and manipulation.',
            'primary_h5p' => ['drag_and_drop', 'mark_the_words', 'find_the_hotspot', 'fill_in_the_blanks'],
        ],
        'project_based' => [
            'label' => 'Project Based',
            'description' => 'Extended authentic work with milestones, evidence, and reflection.',
            'primary_h5p' => ['documentation_tool', 'course_presentation', 'essay'],
        ],
        'flashcard' => [
            'label' => 'Flashcard / Spaced Repetition',
            'description' => 'Strategic review for fluency and long-term memory.',
            'primary_h5p' => ['flash_cards', 'dialog_cards', 'memory_game'],
        ],
        'flipped_classroom' => [
            'label' => 'Flipped Classroom',
            'description' => 'Pre-learning asynchronously followed by guided in-class application.',
            'primary_h5p' => ['interactive_video', 'course_presentation', 'fill_in_the_blanks'],
        ],
        'scenario_based' => [
            'label' => 'Scenario Based',
            'description' => 'Situated decision-making through realistic branching contexts.',
            'primary_h5p' => ['branching_scenario', 'course_presentation'],
        ],
        'spiritual_science' => [
            'label' => 'Spiritual Science',
            'description' => 'Values, mindfulness, wellbeing, and Indian knowledge systems.',
            'primary_h5p' => ['interactive_video', 'questionnaire'],
        ],
        'competency_based' => [
            'label' => 'Skill / Competency Based',
            'description' => 'Progression based on demonstrated performance and evidence.',
            'primary_h5p' => ['documentation_tool', 'audio_recorder'],
        ],
        'concept_sports' => [
            'label' => 'Concept Based - Sports',
            'description' => 'Academic concepts taught through sports contexts and transfer.',
            'primary_h5p' => ['interactive_video', 'drag_and_drop', 'image_hotspot'],
        ],
    ],
    'aliases' => [
        'concept-based' => 'inquiry_based',
        'concept_based' => 'inquiry_based',
        'inquiry-based' => 'inquiry_based',
        'practice-based' => 'activity_based',
        'practice_based' => 'activity_based',
        'visual-learning' => 'art_integrated',
        'story-based' => 'scenario_based',
        'socratic' => 'inquiry_based',
        'gamified' => 'game_based',
        'problem-based' => 'project_based',
        'simulation' => 'scenario_based',
        'audio' => 'experiential',
    ],
    'casel' => ['self_awareness', 'self_management', 'social_awareness', 'relationship_skills', 'responsible_decision_making'],
    'ngss' => ['asking_questions', 'developing_models', 'investigation', 'data_analysis', 'math_computation', 'explanation', 'argumentation', 'communication'],
    'ncdg' => ['PS1', 'PS2', 'EDL1', 'EDL2', 'CM1', 'CM2', 'CM3', 'CM4'],
    'music' => ['music_theory', 'music_performance', 'music_composition', 'music_appreciation'],
    'sports' => ['sports_fitness', 'sports_technical', 'sports_tactical', 'sports_sportsmanship'],
    'finance' => ['finance_literacy', 'finance_products', 'finance_planning', 'finance_investing'],
    'riasec' => ['R', 'I', 'A', 'S', 'E', 'C'],
    'gardner' => ['linguistic', 'logical_mathematical', 'spatial', 'musical', 'bodily_kinesthetic', 'naturalist', 'interpersonal', 'intrapersonal'],
    'h5p' => [
        'interactive_video', 'course_presentation', 'branching_scenario', 'documentation_tool',
        'fill_in_the_blanks', 'drag_and_drop', 'multiple_choice', 'memory_game',
        'flash_cards', 'dialog_cards', 'image_hotspot', 'crossword', 'essay',
        'questionnaire', 'summary', 'audio_recorder', 'agamotto', 'mark_the_words',
        'arithmetic_quiz', 'find_the_hotspot', 'image_sequencing',
    ],
    'coverage' => [
        'inquiry_based' => ['casel' => ['social_awareness'], 'ngss' => ['asking_questions'], 'ncdg' => ['EDL2']],
        'experiential' => ['casel' => ['self_management'], 'ngss' => ['investigation'], 'ncdg' => ['EDL2'], 'sports' => ['sports_fitness']],
        'art_integrated' => ['casel' => ['self_awareness'], 'music' => ['music_theory', 'music_appreciation']],
        'game_based' => ['casel' => ['responsible_decision_making'], 'ncdg' => ['CM1']],
        'activity_based' => ['casel' => ['relationship_skills'], 'ngss' => ['investigation'], 'sports' => ['sports_fitness', 'sports_technical']],
        'project_based' => ['casel' => ['relationship_skills'], 'ngss' => ['communication'], 'ncdg' => ['CM3'], 'finance' => ['finance_planning']],
        'flashcard' => ['casel' => ['self_management'], 'ncdg' => ['EDL1'], 'music' => ['music_theory'], 'finance' => ['finance_literacy']],
        'flipped_classroom' => ['casel' => ['self_management'], 'ngss' => ['communication'], 'ncdg' => ['EDL2']],
        'scenario_based' => ['casel' => ['responsible_decision_making'], 'ngss' => ['argumentation'], 'ncdg' => ['CM1', 'CM4'], 'sports' => ['sports_tactical'], 'finance' => ['finance_products', 'finance_planning']],
        'spiritual_science' => ['casel' => ['self_awareness'], 'ncdg' => ['PS1'], 'music' => ['music_appreciation'], 'sports' => ['sports_sportsmanship']],
        'competency_based' => ['casel' => ['self_management'], 'ngss' => ['investigation'], 'ncdg' => ['CM3'], 'music' => ['music_performance'], 'sports' => ['sports_technical'], 'finance' => ['finance_products']],
        'concept_sports' => ['casel' => ['relationship_skills'], 'ngss' => ['math_computation'], 'ncdg' => ['PS2'], 'sports' => ['sports_tactical']],
    ],
    'finance_activation' => [
        'riasec' => ['C', 'E'],
        'grade_min' => 5,
        'levels' => [
            'finance_literacy' => ['grade_min' => 5, 'grade_max' => 7],
            'finance_products' => ['grade_min' => 7, 'grade_max' => 9],
            'finance_planning' => ['grade_min' => 9, 'grade_max' => 11],
            'finance_investing' => ['grade_min' => 11, 'grade_max' => 12],
        ],
    ],
];
